# Created By Prabin K Datta
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
target 'ChatBot' do
    use_frameworks!
    pod 'AFNetworking', '~> 3.0'
    pod 'SwiftyJSON'
    pod 'AZDialogView'
end
